
#if defined(RENDER_ENGINE_OBJECTS) || defined(RENDER_ENGINE_OBJECT)

#ifndef RENDER_ENGINE_OBJECT

#define RENDER_ENGINE_OBJECT(x) x,

#endif // !RENDER_ENGINE_OBJECT

RENDER_ENGINE_OBJECT(Node)
RENDER_ENGINE_OBJECT(Camera)
RENDER_ENGINE_OBJECT(Bitmap)
RENDER_ENGINE_OBJECT(StaticModel)
RENDER_ENGINE_OBJECT(UIPanel)
RENDER_ENGINE_OBJECT(DbgPoints)



#undef RENDER_ENGINE_OBJECT
#undef RENDER_ENGINE_OBJECTS

#endif